
CREATE TABLE BOARDS (
                Id INT IDENTITY NOT NULL,
                Name NVARCHAR(32) NOT NULL,
                CONSTRAINT PK__BOARDS__3214EC078A4862A1 PRIMARY KEY (Id)
)
CREATE UNIQUE  NONCLUSTERED INDEX UQ__BOARDS__737584F677C62769
 ON BOARDS
 ( Name )


CREATE TABLE ACCOUNTS (
                Id INT IDENTITY NOT NULL,
                AccountName VARCHAR(32) NOT NULL,
                Passcode VARCHAR(32) NOT NULL,
                Type VARCHAR(16) DEFAULT 'Normal' NOT NULL,
                Nickname NVARCHAR(16) NOT NULL,
                CONSTRAINT PK__ACCOUNTS__3214EC07F3B178EE PRIMARY KEY (Id)
)
CREATE UNIQUE  NONCLUSTERED INDEX UQ__ACCOUNTS__406E0D2E9B3FC63F
 ON ACCOUNTS
 ( AccountName )


CREATE TABLE POSTS (
                Id INT IDENTITY NOT NULL,
                BoardId INT NOT NULL,
                OwnerId INT NOT NULL,
                Title NVARCHAR(32) NOT NULL,
                CreateDate DATETIME NOT NULL,
                CreateTime DATETIME NOT NULL,
                UpdateDate DATETIME,
                UpdateTime DATETIME,
                Content NCLOB NOT NULL,
                CONSTRAINT POSTS_pk PRIMARY KEY (Id)
)

CREATE TABLE REPLIES (
                Id INT IDENTITY NOT NULL,
                PostId INT NOT NULL,
                OwnerId INT NOT NULL,
                CreateDate DATETIME NOT NULL,
                CreateTime DATETIME NOT NULL,
                UpdateDate DATETIME,
                UpdateTime DATETIME,
                Content NVARCHAR(1024) NOT NULL,
                CONSTRAINT REPLIES_pk PRIMARY KEY (Id)
)

CREATE TABLE ACCOUNT_BOARD_AUTHORITIES (
                Id INT IDENTITY NOT NULL,
                AccountId INT NOT NULL,
                BoardId INT NOT NULL,
                Authority VARCHAR(16) DEFAULT 'Read' NOT NULL,
                CONSTRAINT PK__ACCOUNT___3214EC0736190747 PRIMARY KEY (Id)
)

ALTER TABLE ACCOUNT_BOARD_AUTHORITIES ADD CONSTRAINT FK__ACCOUNT_B__Board__619B8048
FOREIGN KEY (BoardId)
REFERENCES BOARDS (Id)

ALTER TABLE POSTS ADD CONSTRAINT BOARDS_POSTS_fk
FOREIGN KEY (BoardId)
REFERENCES BOARDS (Id)

ALTER TABLE ACCOUNT_BOARD_AUTHORITIES ADD CONSTRAINT FK__ACCOUNT_B__Accou__60A75C0F
FOREIGN KEY (AccountId)
REFERENCES ACCOUNTS (Id)

ALTER TABLE POSTS ADD CONSTRAINT ACCOUNTS_POSTS_fk
FOREIGN KEY (OwnerId)
REFERENCES ACCOUNTS (Id)

ALTER TABLE REPLIES ADD CONSTRAINT ACCOUNTS_REPLIES_fk
FOREIGN KEY (OwnerId)
REFERENCES ACCOUNTS (Id)

ALTER TABLE REPLIES ADD CONSTRAINT POSTS_REPLIES_fk
FOREIGN KEY (PostId)
REFERENCES POSTS (Id)